# Site settings
baseurl: ""
url: "http://ma08.github.io"
title: BLOB
header-img: img/computer_problems.png
email: thisisma08@gmail.com
description: "A clueless, curious programmer's ramblings"
#twitter_username: SBootstrap

author :
  name : ma08
  github:  ma08
  stackexchange: 3465519
  disqus_shortname: sourya4

#facebook_username:  IronSummitMedia

# Build settings
#markdown: kramdown
markdown: redcarpet-pygments
highlighter: pygments
permalink: /:title/
#permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
